name: phonenumbers_core
description: Phone number parsing & validation plugin written in pure dart
version: 1.0.1
homepage: https://github.com/fonibo/phonenumbers

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  quiver: ^3.0.1

dev_dependencies:
  test: ^1.16.0
