name: phonenumbers
description: Phone number validation and input widget written in pure dart without any native dependency
version: 1.1.1
homepage: https://github.com/fonibo/phonenumbers

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  phonenumbers_core: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
